const repoList = document.getElementById('repo-list');
const loading = document.getElementById('loading');

const langColors = {
    'JavaScript': '#f1e05a',
    'Python': '#3572A5',
    'HTML': '#e34c26',
    'CSS': '#563d7c',
    'TypeScript': '#2b7489',
    'Vue': '#41b883',
    'Java': '#b07219',
    'C++': '#f34b7d',
    'C#': '#178600',
    'C': '#555555',
    'Shell': '#89e051',
    'Lua': '#000080'
};

async function fetchRepos() {
    loading.style.display = 'block';
    repoList.innerHTML = '';

    try {
        // Fetch from the local JSON file generated by the Python script/Action
        const response = await fetch('repos.json');

        if (!response.ok) {
            throw new Error(`Failed to load projects database: ${response.status}`);
        }

        const repos = await response.json();
        renderRepos(repos);

        // Update status text
        const statusEl = document.querySelector('.hud-module.center .scrolling-text');
        if (statusEl) statusEl.innerText = "LOCAL_DB_LOADED :: SYSTEMS_OPTIMAL";

    } catch (error) {
        console.error(error);
        repoList.innerHTML = `<div class="status" style="color: red;">ERROR: DATABASE CORRUPTED OR MISSING. (repos.json not found)</div>`;
    } finally {
        loading.style.display = 'none';
    }
}

function renderRepos(repos) {
    if (repos.length === 0) {
        repoList.innerHTML = '<div class="status">NO_REPOSITORIES_FOUND_IN_DB</div>';
        return;
    }

    repos.forEach(repo => {
        const card = document.createElement('div');
        card.className = 'repo-item';
        card.onclick = () => window.open(repo.html_url, '_blank');

        const langColor = langColors[repo.language] || '#ccc';
        const updatedDate = new Date(repo.updated_at).toLocaleDateString();

        // Truncate description if too long
        let desc = repo.description || 'No description provided.';
        if (desc.length > 100) {
            desc = desc.substring(0, 100) + '...';
        }

        card.innerHTML = `
            <div class="repo-header">
                <div class="repo-name">${repo.name}</div>
                <div class="repo-visibility">${repo.visibility || 'public'}</div>
            </div>
            <div class="repo-desc">${desc}</div>
            <div class="repo-meta">
                ${repo.language ? `
                <div class="repo-stat">
                    <span class="repo-lang-color" style="background-color: ${langColor}"></span>
                    <span>${repo.language}</span>
                </div>` : ''}
                <div class="repo-stat">
                    <span>★ ${repo.stargazers_count}</span>
                </div>
                <div class="repo-stat">
                    <span>UPDATED: ${updatedDate}</span>
                </div>
            </div>
        `;

        repoList.appendChild(card);
    });
}

// Initial fetch
document.addEventListener('DOMContentLoaded', fetchRepos);
